### ISSUE TITLE
Pinch to zoom does not work

### ISSUE THREAD

**Issue by PrasoonPratham** [uditkarode/epsilon#2]

**Comment by uditkarode** [comment]
You flashed the wrong variant

**Comment by PrasoonPratham** [comment]
No, multiple other people seem to have the same issue [here](https://forum.xda-developers.com/t/kernel-updated-25-8-2021-epsilon-4-14-sweet-sweetin.4313573/page-3#post-85547747)

**Comment by uditkarode** [comment]
Multiple people flashed the wrong variant then
If you flashed `_MIUI`/`lowdimen` and have the issue, flash the regular/`highdimen` variant and vice versa

I see someone commented 'Theres Epsilon for MIUI and Epsilon regular is for custom roms and aosp based roms'
This is not true, and I agree the `_MIUI` naming scheme was confusing, which is why I changed it to `lowdimen` and `highdimen` on the Telegram channel

The `_MIUI` variant (now the `highdimen` variant) was supposed to be for ROMs that use MIUI panel dimensions, which does not have to be MIUI, can very well be a custom rom/aosp based rom

**Comment by PrasoonPratham** [comment]
Alright gotcha, will update this.

Thanks for all the effort you've put into building this.
